feat: LinkedIn - Send like to latest profile post
jupyter-naas/awesome-notebooks pull request #2107
Opened 2023-08-03 11:34 UTC by FlorentLvr

This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2106

2023-08-09 14:42 UTC, FlorentLvr commented
@Dr0p42, "ready to review", can you please check this template on your side?

2023-08-09 14:55 UTC, Dr0p42 requested changes

2023-08-10 07:22 UTC, FlorentLvr commented on LinkedIn/LinkedIn_Send_like_to_latest_profile_post.ipynb
> +    "def is_file_exists(dir_path, file_name):\n",
@Dr0p42, thank you for your feedback! I have updated the notebook!

2023-08-11 10:27 UTC, FlorentLvr commented
@Dr0p42, did you have time to review it?

2023-08-11 14:59 UTC, Dr0p42 approved these changes

2023-08-11 14:59 UTC, merged